volumes:
  database:

networks:
  api:
  database:

services:
  crudhousesrentdb:
    image: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: housesrent
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: housesrent
    ports:
      - '3306:3306'
    volumes:
      - database:/var/lib/mysql
      - ./dbscript.sql:/docker-entrypoint-initdb.d/0_init.sql
    networks:
      - database

  crudhousesrentapi:
    image: rafaalberto/crudhousesrentapi:latest
    container_name: crudhousesrentapi
    networks:
      - database
      - api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    environment:
      - DBHOST=crudhousesrentdb
    depends_on:
      - crudhousesrentdb
